on:
  push:
    branches:
      - master  # You can specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: ng test